import type { Metadata } from "next";
import { Inter, Playfair_Display, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "./contex/contex";
import { InventoryProvider } from "./contex/inventory";
import ClientHeader from "./components/client-header";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playfair.variable} ${geistMono.variable} antialiased bg-white text-neutral-800 pt-28`}>
        <AuthProvider>
          <InventoryProvider>
            <ClientHeader />
            {children}
          </InventoryProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
